#ifndef COMMON_H
#define COMMON_H
#define LEFT_OFFSET 10
#define FREQ_MAX 10800
#define FREQ_MIN 8800
#define FREQ_DISPLAY_MIN 8000
#define FREQ_DISPLAY_MAX 11000
#define BACK_COLOR GxEPD_WHITE
#define TEXT_COLOR GxEPD_BLACK
#define QUALITY_MAX_VALUE 1200
#define ROTARY_ENCODER_A_PIN 27
#define ROTARY_ENCODER_B_PIN 26
#define ROTARY_ENCODER_BUTTON_PIN 14
#define ROTARY_ENCODER_STEPS 4
#define ENABLE_POWER_TEF6686_PIN 32
#endif